---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chaoguan.
--- DateTime: 2021/10/11 16:19
---

---@class RMAnimatorFunc
---@field tgt
---@field func

---@class RMAnimatorEvent
---@field _functions table<number,RMAnimatorFunc>
local RMAnimatorEvent = XECS.class("RMAnimatorEvent")

function RMAnimatorEvent:ctor()
    self._functions = {}
end

---@param tgt table
function RMAnimatorEvent:AddListener(tgt, func)
    if not func then
        return
    end
    ---@type RMAnimatorFunc
    local tab = {}
    tab.tgt = tgt
    tab.func = func
    table.insert(self._functions, tab)
end

---@param tgt table
function RMAnimatorEvent:RemoveListener(tgt, func)
    if not func then
        return
    end
    ---@param tab RMAnimatorFunc
    for index, tab in ipairs(self._functions) do
        if tab.func == func and tab.tgt == tgt then
            table.remove(self._functions, index)
            break
        end
    end
end

function RMAnimatorEvent:Invoke(...)
    for _, tab in ipairs(self._functions) do
        if tab then
            if tab.tgt then
                tab.func(tab.tgt, ...)
            else
                tab.func(...)
            end
        end
    end
end

function RMAnimatorEvent:Clear()
    self._functions = {}
end

return RMAnimatorEvent