---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chaoguan.
--- DateTime: 2021/10/9 11:38
---

---@class RMAnimatorParameterType
RMAnimatorParameterType = {
    Float = 1,
    Int = 3,
    Bool = 4,
    Trigger = 9
}

---@type RMAnimatorEvent
local RMAnimatorEvent = require("Runtime.Battle.Logic.RMAnimator.RMAnimatorEvent")

---@class RMAnimatorParameter
---@field name String
---@field type RMAnimatorParameterType
---@field value any
---@field ctrl RMAnimatorController
---@field onValueChanged RMAnimatorEvent parameter:RMAnimatorParameter
local RMAnimatorParameter = XECS.class("RMAnimatorParameter")

---@param name String
---@param type RMAnimatorParameterType
---@param value any
function RMAnimatorParameter:ctor(name, type, value)
    self.name = name
    self.type = type
    self:SetValue(value)
    self.onValueChanged = RMAnimatorEvent()
end

function RMAnimatorParameter:OnStart()
end

function RMAnimatorParameter:OnUpdate(ctrl)
    self.ctrl = ctrl
    if self.type == RMAnimatorParameterType.Trigger then
        self:SetValue(false)
    end
end

function RMAnimatorParameter:OnDestroy()
end

function RMAnimatorParameter:DeepCopy()
    return RMAnimatorParameter.new(self.ctrl, self.name, self.type, self.value)
end

function RMAnimatorParameter:SetValue(value)
    if not value or self.value == value then
        return
    end

    self.value = value
    if self.onValueChanged then
        self.onValueChanged:Invoke(self)
    end
end

return RMAnimatorParameter