---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chaoguan.
--- DateTime: 2021/10/9 11:41
---

local RMClipMotion = require("Runtime.Battle.Logic.RMAnimator.RMClipMotion")

---@class RMBlendTreeChild:RMClipMotion
---@field threshold Float
---@field timeScale Float
---@field cycleOffset Float
---@field directBlendParameter String
---@field mirror Boolean
local RMBlendTreeChild = XECS.class("RMBlendTreeChild", RMClipMotion)

---@param clipEvents FrameEvent[]
function RMBlendTreeChild:ctor(ctrl, threshold, clipInfo, clipEvents)
    RMClipMotion.ctor(self, ctrl, clipInfo, clipEvents)
    self.threshold = threshold
    self._ctrl = ctrl
end

function RMBlendTreeChild:DeepCopy()
    return RMBlendTreeChild.new(self._ctrl, self.threshold, self._clipInfo, self._clipEvents)
end

return RMBlendTreeChild