---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chaoguan.
--- DateTime: 2021/10/9 11:41
---

---@class RMMotion
---@field weight Float
---@field length Float
---@field isLoop Boolean
---@field repeatedCount Int
---@field normalizedTime Float
local RMMotion = XECS.class("RMMotion")

function RMMotion:ctor()
end

function RMMotion:OnEnter(startingTime)
end

function RMMotion:SetTime(runningTime)
end

function RMMotion:OnExit()
end

function RMMotion:OnDestroy()
end

function RMMotion:SetWeight(weight)
end

function RMMotion:Evaluate()
end

function RMMotion:Rebuild(ctrl, eventNotifyFunc)
end

return RMMotion